### ISSUE TITLE
AttributeError: module 'rmf_adapter' has no attribute 'easy_full_control'

### ISSUE THREAD

**Issue by TheConstructAi** [open-rmf/roscon_workshop#17]
## Bug report
File "/home/user/ros2_ws/install/barista_fleet_adapter/lib/python3.10/site-packages/barista_fleet_adapter/fleet_adapter.py", line 131, in get_configuration
[fleet_adapter-16]     configuration = adpt.easy_full_control.Configuration(
[fleet_adapter-16] AttributeError: module 'rmf_adapter' has no attribute 'easy_full_control'

When starting RMF that's what happens using the easy_adapter option ( which is using the custom adapter )

Any ideas?

- Operating system and version: Ubuntu 22
- OpenRMF installation type: SOurce
- OpenRMF version or commit hash: main
- ROS distribution and version: Humble

**Comment by Yadunund** [comment]
You'll need to checkout the branches to those specified in the rmf.repos file in this repository.
https://github.com/open-rmf/roscon_workshop/blob/main/rmf.repos

**Comment by TheConstructAi** [comment]
Installing that I get this error:

Could not checkout ref 'yadu/easy_full_control': fatal: invalid reference: yadu/easy_full_control

**Comment by Yadunund** [comment]
Thanks for highlighting this issue. The problem was two fold
1) The `yadu/easy_full_control` branch was deleted after the merge as you pointed out. -> I have restored this branch
2) The linking error is caused because `nlohamnn_json_schema_vendor pkg was [updated recently ](https://github.com/open-rmf/nlohmann_json_schema_validator_vendor/pull/12) which then requires rmf_websocket and rmf_task_ros2 to also be updated. The latter was done in this [PR](https://github.com/open-rmf/rmf_ros2/pull/246/files). -> I've updated the `yadu/easy_full_control` branch to incorporate these changes.

I just did a clean build on my machine with the rmf.repos file in this repo and the build is successful. Let me know if you still encounter an issue.

**Comment by TheConstructAi** [comment]
Thanks, as soon as we have time to go back , we will try this. Any case, I imagine this will be in the main branch in the future?

**Comment by Yadunund** [comment]
Yes the plain is to merge this feature into `main` after more exhaustive testing and code reviews. I'll close the ticket now but feel free to reopen if the issue persists.
